INSERT INTO setores (nome) VALUES ('ADEPESE');
INSERT INTO setores (nome) VALUES ('ADM - Núc. 1º Atendimento');
INSERT INTO setores (nome) VALUES ('AdministraTivo');
INSERT INTO setores (nome) VALUES ('Almoxarifado');
INSERT INTO setores (nome) VALUES ('ASCOM');
INSERT INTO setores (nome) VALUES ('ASPLAN');
INSERT INTO setores (nome) VALUES ('Câmara Criminal');
INSERT INTO setores (nome) VALUES ('Central de Conciliação');
INSERT INTO setores (nome) VALUES ('Cerimonial');
INSERT INTO setores (nome) VALUES ('CIAPS Psicologia');
INSERT INTO setores (nome) VALUES ('CIAPS Social');
INSERT INTO setores (nome) VALUES ('Contabilidade');
INSERT INTO setores (nome) VALUES ('Contratos e Convênios');
INSERT INTO setores (nome) VALUES ('Coordenação Central');
INSERT INTO setores (nome) VALUES ('Corregedoria Geral');
INSERT INTO setores (nome) VALUES ('CRLS Administrativo');
INSERT INTO setores (nome) VALUES ('CRLS Técnica');
INSERT INTO setores (nome) VALUES ('Defensoria Geral');
INSERT INTO setores (nome) VALUES ('DTI');
INSERT INTO setores (nome) VALUES ('Escola da Defensoria Pública');
INSERT INTO setores (nome) VALUES ('Estágios');
INSERT INTO setores (nome) VALUES ('Financeiro');
INSERT INTO setores (nome) VALUES ('Fórum Barra dos Coqueiros');
INSERT INTO setores (nome) VALUES ('Fórum Boquim');
INSERT INTO setores (nome) VALUES ('Fórum Campo do Brito');
INSERT INTO setores (nome) VALUES ('Fórum Canidé');
INSERT INTO setores (nome) VALUES ('Fórum Capela');
INSERT INTO setores (nome) VALUES ('Fórum Carmópolis');
INSERT INTO setores (nome) VALUES ('Fórum Cristinápolis');
INSERT INTO setores (nome) VALUES ('Fórum D.I.A.');
INSERT INTO setores (nome) VALUES ('Fórum de Maruim');
INSERT INTO setores (nome) VALUES ('Fórum Estância');
INSERT INTO setores (nome) VALUES ('Fórum Frei Paulo');
INSERT INTO setores (nome) VALUES ('Fórum Gararu');
INSERT INTO setores (nome) VALUES ('Fórum Glória');
INSERT INTO setores (nome) VALUES ('Fórum Gumercindo Bessa');
INSERT INTO setores (nome) VALUES ('Fórum Itabaiana');
INSERT INTO setores (nome) VALUES ('Fórum Itabaianinha');
INSERT INTO setores (nome) VALUES ('Fórum Itaporanga');
INSERT INTO setores (nome) VALUES ('Fórum Japaratuba');
INSERT INTO setores (nome) VALUES ('Fórum Japoatã');
INSERT INTO setores (nome) VALUES ('Fórum Lagarto');
INSERT INTO setores (nome) VALUES ('Fórum Laranjeiras');
INSERT INTO setores (nome) VALUES ('Fórum Maracaju');
INSERT INTO setores (nome) VALUES ('Fórum Marcos Freire II');
INSERT INTO setores (nome) VALUES ('Fórum Neópolis');
INSERT INTO setores (nome) VALUES ('Fórum Orlando Dantas');
INSERT INTO setores (nome) VALUES ('Fórum Parque dos Faróis');
INSERT INTO setores (nome) VALUES ('Fórum Pirambu');
INSERT INTO setores (nome) VALUES ('Fórum Poço Redondo');
INSERT INTO setores (nome) VALUES ('Fórum Propriá');
INSERT INTO setores (nome) VALUES ('Fórum Propriá');
INSERT INTO setores (nome) VALUES ('Fórum Ribeirópolis');
INSERT INTO setores (nome) VALUES ('Fórum Salgado');
INSERT INTO setores (nome) VALUES ('Fórum Santa Maria');
INSERT INTO setores (nome) VALUES ('Fórum Santana de São Francisco');
INSERT INTO setores (nome) VALUES ('Fórum Santo Amaro');
INSERT INTO setores (nome) VALUES ('Fórum Santos Dumont');
INSERT INTO setores (nome) VALUES ('Fórum São Cristovão');
INSERT INTO setores (nome) VALUES ('Fórum Simão Dias');
INSERT INTO setores (nome) VALUES ('Fórum Socorro');
INSERT INTO setores (nome) VALUES ('Fórum Tobias Barreto');
INSERT INTO setores (nome) VALUES ('Fórum UFS');
INSERT INTO setores (nome) VALUES ('Juizado da Criança e Adolescente');
INSERT INTO setores (nome) VALUES ('Licitações');
INSERT INTO setores (nome) VALUES ('Núcleo 1º Atendimento');
INSERT INTO setores (nome) VALUES ('Núcleo da Criança e Adolescente');
INSERT INTO setores (nome) VALUES ('Núcleo da Saúde');
INSERT INTO setores (nome) VALUES ('Núcleo de Direitos Humanos e Inc. Social');
INSERT INTO setores (nome) VALUES ('Núcleo de Execuções Penais');
INSERT INTO setores (nome) VALUES ('Núcleo de Flagrantes e Presos Provisório');
INSERT INTO setores (nome) VALUES ('Núcleo de Inquéritos Administrativos');
INSERT INTO setores (nome) VALUES ('Núcleo de Movimento de Bairros');
INSERT INTO setores (nome) VALUES ('Núcleo do Consumidor');
INSERT INTO setores (nome) VALUES ('Núcleo do Direito da Mulher');
INSERT INTO setores (nome) VALUES ('Patrimônio');
INSERT INTO setores (nome) VALUES ('Peticionamento Integrado');
INSERT INTO setores (nome) VALUES ('Planejamento');
INSERT INTO setores (nome) VALUES ('Protocolo');
INSERT INTO setores (nome) VALUES ('Recepção Central');
INSERT INTO setores (nome) VALUES ('Recepção Sede');
INSERT INTO setores (nome) VALUES ('Recursos Humanos');
INSERT INTO setores (nome) VALUES ('Secretaria Geral');
INSERT INTO setores (nome) VALUES ('Subdefensoria Geral');
INSERT INTO setores (nome) VALUES ('Transportes');
INSERT INTO setores (nome) VALUES ('Triagem 1º Atendimento');
INSERT INTO setores (nome) VALUES ('Triagem Saúde');
INSERT INTO setores (nome) VALUES ('Tribunal De Justiça');