import { Metadata } from "next";

//metadata
export const metadata: Metadata = {
  title: "Home - estudo sobre nextjs", // titulo da aba
  description: "Generated by create next app",
  openGraph: {
    title: "Home - estudo sobre nextjs", // titulo para compartilhar o link do site
    description: "Generated by create next app", // da para colocar uma imagem de preview com o termo " image: [link da imagem] "
  },
  robots: {
    follow: true,
    index: true,
    nocache: true,
    googleBot: {
      index: true,
      follow: true
    }
  },
}

export default function Home() {
  return (
    <div>
      <h1>Home</h1>
    </div>
  );
}